# Generated by Django 2.2.13 on 2021-01-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto_nombrecomprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombreComprador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
